services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_study4cash
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - server_network
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  app:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: go_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mariadb
      DB_NAME: ${DB_NAME}
      TOKEN_SECRET: ${TOKEN_SECRET}
    networks:
      - server_network
    depends_on:
      mariadb:
        condition: service_healthy
  openAPIDocs:
    image: swaggerapi/swagger-ui
    ports:
      - "5050:8080"
    environment:
      SWAGGER_JSON: /foo/openapi.yaml
    volumes:
      - ./server/docs/openAPI.yml:/foo/openapi.yaml:ro
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: client_study4cash
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      API_URL: ${API_URL}

volumes:
  mariadb_data:

networks:
  server_network:
    driver: bridge
